### ISSUE TITLE
기능 정의

### ISSUE THREAD

**Issue by thenaun-pooh** [thenaun-workspace/somaeja#17]
크게 어떤 기능이 있을지 
정리를 해서 앱쪽에 전달 해줘야 할 것 같습니다.
(12 말까지)

시간 나실 때 정리 해주세요~ㅎ

**Comment by Lob-dev** [comment]
넵..! 상세한 URL 제공 정보 같은 것보단 기능 명세에 대해서만 정리하면 되는 것인가요??

**Comment by thenaun-pooh** [comment]
넵~
