### ISSUE TITLE
Location 도메인 개발

### ISSUE THREAD

**Issue by Lob-dev** [thenaun-workspace/somaeja#23]
도메인에서 개발하여야할 기능
- 도로명주소 DB 데이터 활용
- Entity, Mapper 개발
    - (우선은 서울) 광역시, 00도 명, 00군, 00구 명, 읍면동 명까지만 사용.
        - 서울시 강동구 천호동
- Service 작성 및 Post 연동

**Comment by thenaun-pooh** [comment]
resolve #25
