### ISSUE TITLE
Location DB, Entity, Mapper 개발

### ISSUE THREAD

**Issue by Lob-dev** [thenaun-workspace/somaeja#24]
### **Feature Description**
<hr/>

도로명주소 DB 데이터 활용 및 Entity, Mapper 개발을 진행합니다.
+ 도로명주소 DB 데이터에서 서울시 범위의 필요 데이터 추출.
+ Entity, Mapper 개발

### **Feature Develop Progress**
<hr/>

DB 데이터 추출 -> Entity 작성 -> Mapper 작성

**Comment by thenaun-pooh** [comment]
resolve #25
