### ISSUE TITLE
Logging 적용

### ISSUE THREAD

**Issue by Lob-dev** [thenaun-workspace/somaeja#36]
### Feature Descrption
---

application에 logging을 적용합니다.
+ Logging 학습
+ boot 기본 의존 Library인 slf4j, Logback을 사용하여 적용한다. 

### Feature Develop Progress
---

**Comment by thenaun-pooh** [comment]
시간 괜찮으실 때 아래 조사 한 번 해보셔도 좋을 것 같은데요

- System.out.println vs logging
- slf4j
- Logback vs log4j2

**Comment by Lob-dev** [comment]
넵 알겠습니다!

**Comment by Lob-dev** [comment]
slf4j, Logback, log4j2, prinln vs logging 에 대해서 정리하였습니다.

https://www.notion.so/Logging-slf4j-Logback-Framework-53547a3a8c994402926b68cd37356bae#ba264c3a8ee34fa8a5ee164d81186c56

**Comment by thenaun-pooh** [comment]
@Lob-dev 헉스 해당 노션 페이지가 보이지 않네요 ㅜ 혹시 권한 한 번 부탁드려도 될까요

**Comment by Lob-dev** [comment]
@thenaun-pooh 아 페이지 공개가 안되어 있었습니다..! 공개 설정하였습니다!

**Comment by thenaun-pooh** [comment]
@Lob-dev 조사 잘하셨네요 ㅎㅎ
프로젝트에는 log4j2로 적용을 해볼까요?
