### ISSUE TITLE
User 도메인 개발 구상

### ISSUE THREAD

**Issue by Lob-dev** [thenaun-workspace/somaeja#39]
### 도메인에서 개발하여야할 기능
---
+ User 생성
+ User 로그인, 로그아웃
+ User 조회
+ User 삭제
+ User 수정
+ 각 URI 별 인증, 인가

### 기타사항
---
+ 기존 개발 로직과 연동합니다.
+ 우선적으로 HttpSession을 사용하여 인증, 인가 처리를 구현합니다.
  + 이후 Spring Security를 사용하여 변경합니다.

### 도메인 작업 순서
---
+ User Entity -> Security config, URI 권한 설정  -> User Create (비밀번호 암호화) -> User Find -> User Delete 
+  -> User Modify -> User Login -> User Logout

**Comment by thenaun-pooh** [comment]
먼저 쿠키 + 세션 방식으로 인증 정보를 유지 했으면 합니다

**Comment by Lob-dev** [comment]
넵..! 열심히 레퍼런스를 찾아보고 있습니다..
