### ISSUE TITLE
User 삭제 기능 개발

### ISSUE THREAD

**Issue by Lob-dev** [thenaun-workspace/somaeja#42]
### Feature Description
---

User 정보를 삭제하는 로직들을 개발합니다.

- User Mapper
    - User 삭제에 대한 xml 작성 및 테스트를 진행합니다.
    - Soft, Hard Delete 중 어떤 것을 선택할지 고려해봅니다.
- User Service
    - User 삭제에 대한 메서드를 작성합니다.
    - 관련 Custom Exception을 생성하고 Handler를 작성합니다.
- User Controller
    - delete API 생성
    - 통합 테스트 작성

### Feature Develop Progress
---
User Mapper delete -> User Mapper delete 테스트 -> User Service  delete -> Custom Exception 작성 -> Handler 작성
User Controller delete api -> 통합 테스트 작성

**Comment by thenaun-pooh** [comment]
History정보를 계속 보관 하기 보다는 일정 기간이 지나면 날려주는 편이 좋기 때문에
오랜된 데이터는 나중에 배치성으로 지워주거나 
디비 프로시저로 날려주는 것도 나쁘지 않겠네요
(추후 고도화..)
