### ISSUE TITLE
Post 도메인 개발

### ISSUE THREAD

**Issue by Lob-dev** [thenaun-workspace/somaeja#6]
도메인에서 개발하여야할 기능

- Post 생성
- Post 조회
    - title 기준 조회
    - user 기준 조회
    - location 기준 조회 (메인 페이지)
- Post 삭제
- Post 수정

기타사항

- Location, User 정보는 우선 Mocking 하여 데이터를 저장합니다.
- 테스트 코드를 우선적으로 작성하여 개발할 지, 기능을 개발하고 테스트 코드를 작성할 지 고민하고 있습니다.

도메인 작업 순서

- Post Entity -> Post 생성 -> 조회 -> 수정 -> 삭제 순으로 개발하려고 합니다!

**Comment by thenaun-pooh** [comment]
> title 기준 조회

추후 검색기능을 염두하신거죠??
때에 따라서는 게시글 본문에 내용도 검색 가능하게끔 해야 할 수도 있겠네요 ㅎㅎ (요건 추후 고도화)

> 테스트 코드를 우선적으로 작성하여 개발할 지, 기능을 개발하고 테스트 코드를 작성할 지 고민하고 있습니다.

포스트는 test code를 먼저 짜는 TDD 방식으로 해보고요
다른 도메인은 또 다르게도 해보죠
그런다음  석현님이 느낀점을 이야기 해보는 것도 괜찮겠어요

**Comment by thenaun-pooh** [comment]
@Lob-dev 좋습니다~!
시작해보죠  ㅎ

**Comment by Lob-dev** [comment]
넵 알겠습니다!
